services:
  notification:
    build: .
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notification_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Umobolnica93

      ENCRYPTION_SERVICE_BASE_URL: http://encryption:8082/encryption
      SERVER_SERVICE_BASE_URL: http://server:8031/api/
    networks:
      - chat-net
    depends_on:
      postgres:
        condition:
          service_healthy

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Umobolnica93
    ports:
      - "5432:5432"
    volumes:
      - notification_pgdata:/var/lib/postgresql/data
    networks:
      - chat-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  notification_pgdata:

networks:
  chat-net:
    external: true
